markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Henrik Mühe
paginate: 5
production_url : http://muehe.org
description: "Everything concerning Henrik Mühe."
disqus_shortname: henrik-muehe
analytics: UA-501318-13
gauges:
author :
  name : Henrik Mühe
  github : henrik-muehe
  twitter : henrikm85
  email: henrik.muehe@gmail.com
